export interface Destination {
  id: string;
  slug: string;
  name: string;
  region: string;
  type: "domestic" | "international";
  country: string;
  price: number;
  priceLabel: string;
  image: string;
  tagline: string;
  description: string;
  bestTime: string;
  duration: string;
  type_label: string;
  difficulty?: string;
  itinerary: { day: number; title: string; description: string }[];
  includes: string[];
  heroImage: string;
}

export const destinations: Destination[] = [
  {
    id: "wayanad",
    slug: "wayanad",
    name: "Wayanad",
    region: "Kerala, India",
    type: "domestic",
    country: "India",
    price: 500,
    priceLabel: "₹500 onwards",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1920&q=90",
    tagline: "Mist-Covered Highlands",
    description: "Wayanad is a lush highland district in Kerala, where spice-scented forests meet cascading waterfalls and tribal heritage. Nestled amid the Western Ghats, it offers misty mornings, wildlife sanctuaries, and serene bamboo forests that feel untouched by time.",
    bestTime: "October – March",
    duration: "2–3 Days",
    type_label: "Nature & Wildlife",
    includes: ["Hotel Accommodation", "Transfers", "Breakfast & Dinner", "Forest Safari", "24/7 Support"],
    itinerary: [
      { day: 1, title: "Arrive in Wayanad", description: "Transfer from Kochi/Calicut airport. Check in to a jungle resort. Evening stroll through spice plantations. Welcome dinner with local Kerala cuisine." },
      { day: 2, title: "Waterfalls & Wildlife", description: "Morning visit to Soochipara and Meenmutty Falls. Afternoon Jeep safari at Muthanga Wildlife Sanctuary — spot elephants, deer, and wild boar. Sunset at Chembra Peak viewpoint." },
      { day: 3, title: "Heritage & Departure", description: "Morning visit to Edakkal Caves with prehistoric rock engravings. Local spice market tour. Afternoon departure transfer." },
    ],
  },
  {
    id: "munnar",
    slug: "munnar",
    name: "Munnar",
    region: "Kerala, India",
    type: "domestic",
    country: "India",
    price: 700,
    priceLabel: "₹700 onwards",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=1920&q=90",
    tagline: "Green Tea Hills of Kerala",
    description: "Munnar is Kerala's crown jewel — a high-altitude paradise where rolling tea plantations stretch as far as the eye can see. At 1,600 metres above sea level, the cool misty air, rare Neelakurinji blooms, and the aromatic waft of fresh tea leaves make it an unforgettable escape.",
    bestTime: "September – March",
    duration: "2–4 Days",
    type_label: "Hill Station",
    includes: ["Hotel Accommodation", "Transfers", "Breakfast", "Tea Estate Tour", "24/7 Support"],
    itinerary: [
      { day: 1, title: "Arrive & Breathe", description: "Scenic drive from Kochi through mountain roads. Check in to a tea estate bungalow. Evening stroll through the plantation. Hot tea tasting session." },
      { day: 2, title: "Tea, Peaks & Waterfalls", description: "Morning visit to Tata Tea Museum. Hike to Anamudi Peak viewpoint — highest in South India. Afternoon at Attukad and Lakkam Waterfalls." },
      { day: 3, title: "Wildlife & Local Culture", description: "Early morning safari at Eravikulam National Park — home of the Nilgiri Tahr. Visit Mattupetty Dam and Echo Point. Local spice shopping before departure." },
    ],
  },
  {
    id: "kodaikanal",
    slug: "kodaikanal",
    name: "Kodaikanal",
    region: "Tamil Nadu, India",
    type: "domestic",
    country: "India",
    price: 1200,
    priceLabel: "₹1,200 onwards",
    image: "https://images.unsplash.com/photo-1626016752628-e78d0e3a34bc?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1626016752628-e78d0e3a34bc?w=1920&q=90",
    tagline: "Princess of Hill Stations",
    description: "Kodaikanal sits at 2,133 metres on the Palani Hills of Tamil Nadu, a serene escape beloved for its star-shaped lake, forest walks, and colonial-era charm. Mist rolls in from the valleys each afternoon, turning the hillside into a dreamlike landscape of pine, eucalyptus, and rhododendron.",
    bestTime: "April – June, September – November",
    duration: "3–4 Days",
    type_label: "Hill Station",
    includes: ["Hotel Accommodation", "Transfers", "Breakfast", "Boat Ride", "24/7 Support"],
    itinerary: [
      { day: 1, title: "Arrival & Lake Walk", description: "Drive from Madurai or Coimbatore. Check in and evening walk around the star-shaped Kodaikanal Lake. Boat ride at sunset." },
      { day: 2, title: "Viewpoints & Forests", description: "Morning visit to Coaker's Walk for dramatic valley views. Explore Bryant Park flower gardens. Pillar Rocks and Bear Shola Falls in the afternoon." },
      { day: 3, title: "Waterfalls & Valley", description: "Day trip to Silver Cascade Falls. Visit Berijam Lake with permit. Evening shopping for homemade chocolates and eucalyptus oils." },
      { day: 4, title: "Sunrise & Departure", description: "Early morning sunrise from Dolphin's Nose viewpoint. Light breakfast and transfer to departure point." },
    ],
  },
  {
    id: "ooty",
    slug: "ooty",
    name: "Ooty",
    region: "Tamil Nadu, India",
    type: "domestic",
    country: "India",
    price: 900,
    priceLabel: "₹900 onwards",
    image: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=1920&q=90",
    tagline: "Queen of the Nilgiris",
    description: "Ooty — officially Udhagamandalam — is the iconic hill station in the Nilgiri Mountains, known for its UNESCO-listed toy train, emerald tea gardens, and colonial British bungalows. The annual flower show draws visitors from across India, while the Nilgiri Biosphere Reserve offers rich biodiversity.",
    bestTime: "October – June",
    duration: "2–3 Days",
    type_label: "Hill Station",
    includes: ["Hotel Accommodation", "Transfers", "Breakfast", "Toy Train Ticket", "24/7 Support"],
    itinerary: [
      { day: 1, title: "Toy Train & Arrival", description: "Iconic UNESCO Nilgiri Mountain Railway toy train ride from Mettupalayam. Arrive in Ooty, check in. Evening stroll at Ooty Lake." },
      { day: 2, title: "Gardens & Viewpoints", description: "Morning at Government Botanical Gardens (150+ acres). Doddabetta Peak — highest in Nilgiris at 2,637m. Tea factory visit and tasting session." },
      { day: 3, title: "Wildlife & Departure", description: "Morning safari at Mudumalai Tiger Reserve. Local Toda tribal village interaction. Transfer to departure point." },
    ],
  },
  {
    id: "kashmir",
    slug: "kashmir",
    name: "Kashmir",
    region: "Jammu & Kashmir, India",
    type: "domestic",
    country: "India",
    price: 8000,
    priceLabel: "₹8,000 onwards",
    image: "https://images.unsplash.com/photo-1593181629936-11c609b8db9b?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1593181629936-11c609b8db9b?w=1920&q=90",
    tagline: "Heaven on Earth",
    description: "Kashmir is India's most breathtaking paradise — a valley of snow-capped Himalayas, sapphire lakes, saffron fields, and shikaras gliding at dawn. The sheer grandeur of Dal Lake at sunrise, the flower-carpeted Gulmarg meadows in summer, and the deep powder snow that blankets Pahalgam in winter make Kashmir an experience unlike any other in India.",
    bestTime: "March – October (Summer) / December – February (Snow)",
    duration: "5–7 Days",
    type_label: "Adventure & Scenic",
    includes: ["Flights from Kerala", "Houseboat Stay", "Hotel Accommodation", "Transfers", "All Meals", "Shikara Ride", "24/7 Support"],
    itinerary: [
      { day: 1, title: "Arrival in Srinagar", description: "Fly from Kerala to Srinagar. Transfer to houseboat on Dal Lake. Evening Shikara ride on the lake. Sunset over the Himalayan skyline." },
      { day: 2, title: "Dal Lake & Old City", description: "Morning floating vegetable market by Shikara. Visit Shankaracharya Temple. Explore Hazratbal Shrine and old Srinagar bazaars. Traditional wazwan dinner." },
      { day: 3, title: "Gulmarg Excursion", description: "Full day in Gulmarg — Asia's highest gondola ride to Apharwat Peak (4,200m). Snow activities in winter, meadow walks in summer." },
      { day: 4, title: "Pahalgam Valley", description: "Drive through Saffron Fields of Pampore. Arrive in Pahalgam — the Valley of Shepherds. Horse ride along Lidder River. Evening bonfire at the campsite." },
      { day: 5, title: "Betaab Valley & Aru", description: "Visit Betaab Valley (Bollywood's favourite location), Aru Valley, and Chandanwari. Photography of the meadows and mountain streams." },
      { day: 6, title: "Mughal Gardens", description: "Tour the legendary Mughal Gardens — Shalimar Bagh, Nishat Bagh, and Chashme Shahi. Afternoon free for shopping: pashmina, saffron, walnut wood crafts." },
      { day: 7, title: "Departure", description: "Morning at leisure. Transfer to Srinagar airport for return flight to Kerala." },
    ],
  },
  {
    id: "manali",
    slug: "manali",
    name: "Manali",
    region: "Himachal Pradesh, India",
    type: "domestic",
    country: "India",
    price: 7500,
    priceLabel: "₹7,500 onwards",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1920&q=90",
    tagline: "Adventure Capital of the Himalayas",
    description: "Manali is the ultimate adventure destination — where the Beas River crashes through pine valleys, glaciers loom at 13,000 feet, and the legendary Rohtang Pass offers one of India's most dramatic road journeys. From paragliding over Solang Valley to camping under a billion stars, Manali delivers raw Himalayan magic.",
    bestTime: "October – June",
    duration: "5–6 Days",
    type_label: "Adventure & Trekking",
    includes: ["Flights from Kerala", "Hotel Accommodation", "Transfers", "Breakfast & Dinner", "Adventure Activities", "24/7 Support"],
    itinerary: [
      { day: 1, title: "Arrive in Manali", description: "Fly to Delhi, overnight bus or fly to Bhuntar/Kullu. Arrive Manali. Check in. Evening walk along Mall Road. Explore Old Manali cafes." },
      { day: 2, title: "Solang Valley", description: "Morning drive to Solang Valley for paragliding, zorbing, and rope activities. Afternoon Hadimba Devi Temple visit. Evening relaxation." },
      { day: 3, title: "Rohtang Pass", description: "Full day excursion to Rohtang Pass (3,978m) — snow-covered landscapes, yak rides, and panoramic Himalayan views. *Permits required — arranged by Trippy." },
      { day: 4, title: "Kasol & Kheerganga", description: "Drive to Kasol village — the little Israel of India. Short hike to riverside camps. Evening around the campfire." },
      { day: 5, title: "Vashisht & Old Manali", description: "Morning dip in Vashisht hot springs. Explore Buddhist monasteries in Old Manali. Shopping for Kullu shawls and mountain gear." },
      { day: 6, title: "Departure", description: "Transfer to Bhuntar Airport or Volvo bus to Delhi for onward flight to Kerala." },
    ],
  },
  {
    id: "sar-pass",
    slug: "sar-pass",
    name: "Sar Pass Trek",
    region: "Himachal Pradesh, India",
    type: "domestic",
    country: "India",
    price: 6500,
    priceLabel: "₹6,500 onwards",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1920&q=90",
    tagline: "The Epic Himalayan Trek",
    description: "The Sar Pass Trek (4,250m) is one of India's most celebrated high-altitude trails, taking trekkers through dense forest, alpine meadows, frozen lakes, and one of the most dramatic snowy descents in the Himalayas. Starting from Kasol, it's a 5-day odyssey of raw mountain wilderness.",
    bestTime: "May – June",
    duration: "5–6 Days (Trek)",
    type_label: "High-Altitude Trek",
    difficulty: "Moderate to Difficult",
    includes: ["Trek Permit", "All Meals on Trek", "Camping Equipment", "Expert Guide", "Porter Support", "24/7 Support"],
    itinerary: [
      { day: 1, title: "Kasol → Grahan Village", description: "Fly to Delhi, overnight bus to Kasol. Trek begins at Kasol. Ascend through dense cedar forest to Grahan village (2,730m). Camp overnight." },
      { day: 2, title: "Grahan → Min Thatch", description: "Steep climb through rhododendron forests. Arrive at Min Thatch meadows (3,680m). Snow patches begin. Stunning valley views." },
      { day: 3, title: "Min Thatch → Nagaru", description: "Ascent through thick snow. Cross frozen streams. Camp at Nagaru (3,800m) — night temperatures drop to -5°C. Stargazing at high altitude." },
      { day: 4, title: "Nagaru → Sar Pass Summit → Biskeri Thatch", description: "Summit day. Reach Sar Pass (4,250m) for panoramic Himalayan views. Epic 45-degree snow descent to Biskeri Thatch meadows." },
      { day: 5, title: "Biskeri → Barshaini → Kasol", description: "Descend through Biskeri meadows. Exit at Barshaini village. Transfer back to Kasol. Celebration dinner." },
      { day: 6, title: "Departure", description: "Overnight bus to Delhi for return flight to Kerala." },
    ],
  },
  {
    id: "bali",
    slug: "bali",
    name: "Bali",
    region: "Indonesia",
    type: "international",
    country: "Indonesia",
    price: 45000,
    priceLabel: "₹45,000 onwards",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1920&q=90",
    tagline: "Island of the Gods",
    description: "Bali is one of the world's most enchanting islands — a place where ancient Hindu temples perch on sea-cliffs, emerald rice terraces roll through hillside villages, and the gentle Balinese spirit infuses every sunset. From the art galleries of Ubud to the surf breaks of Seminyak and the sacred shores of Uluwatu, Bali offers a rare fusion of culture, nature, and pure soul.",
    bestTime: "April – October",
    duration: "6–8 Days",
    type_label: "Beach & Culture",
    includes: ["International Flights", "Hotel/Villa Accommodation", "Airport Transfers", "Breakfast Daily", "Cultural Tours", "24/7 Support"],
    itinerary: [
      { day: 1, title: "Arrival in Bali", description: "Fly from Kerala (Kochi/Trivandrum) via Singapore or Kuala Lumpur to Ngurah Rai Airport. Transfer to your villa in Seminyak. Sunset at Petitenget Beach." },
      { day: 2, title: "Ubud Art & Temples", description: "Drive to Ubud — visit the Monkey Forest, Tegalalang Rice Terrace, and Tirta Empul holy spring temple. Traditional Kecak dance at sunset." },
      { day: 3, title: "Mt. Batur Sunrise Trek", description: "3am departure for the active volcano hike. Reach summit (1,717m) for one of Southeast Asia's most spectacular sunrises. Breakfast cooked on volcanic steam." },
      { day: 4, title: "Uluwatu & Cliffside", description: "Drive south to Uluwatu Temple perched on a 70m cliff. Watch the sea eagles. Evening Kecak fire dance. Jimbaran Bay seafood dinner on the beach." },
      { day: 5, title: "Beach & Water Sports", description: "Full day in Nusa Dua — water sports, snorkelling, or simply relaxing on white-sand beaches. Optional day trip to Nusa Penida island." },
      { day: 6, title: "Tanah Lot & Farewell", description: "Morning at Tanah Lot — the iconic sea temple at sunrise. Final shopping at Seminyak boutiques. Farewell dinner." },
      { day: 7, title: "Departure", description: "Transfer to Ngurah Rai Airport for return flight to Kerala." },
    ],
  },
  {
    id: "maldives",
    slug: "maldives",
    name: "Maldives",
    region: "Indian Ocean",
    type: "international",
    country: "Maldives",
    price: 75000,
    priceLabel: "₹75,000 onwards",
    image: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1920&q=90",
    tagline: "Pure Ocean Luxury",
    description: "The Maldives is the world's most ultimate escape — 1,200 coral islands scattered across the Indian Ocean, each one a perfect crescent of white sand and turquoise water. Overwater bungalows, bioluminescent beaches, and the most biodiverse coral reefs on Earth make this the definition of luxury. Trippy specialises in getting Kerala travelers here without the usual luxury agency markup.",
    bestTime: "November – April",
    duration: "4–6 Days",
    type_label: "Luxury Beach",
    includes: ["International Flights", "Resort/Overwater Villa", "Seaplane/Speedboat Transfer", "Full Board", "Snorkeling & Diving", "24/7 Support"],
    itinerary: [
      { day: 1, title: "Arrive in Paradise", description: "Fly from Kerala to Velana International Airport, Malé. Seaplane or speedboat transfer to your resort island. Champagne welcome, check-in, and first sunset from your overwater deck." },
      { day: 2, title: "Reef & Snorkeling", description: "Morning house reef snorkeling with reef sharks and manta rays. Afternoon dolphin watching cruise. Sunset fishing trip with the resort." },
      { day: 3, title: "Dive Day", description: "Full day PADI certified diving or intro dive for beginners. Explore UNESCO biosphere reserves. Evening bioluminescent beach walk." },
      { day: 4, title: "Island Hopping", description: "Speedboat to a local Maldivian island — experience authentic island culture, local cuisine, and freshwater lagoons. Sandbank picnic on a deserted atoll." },
      { day: 5, title: "Relaxation & Spa", description: "Day at leisure — world-class overwater spa treatments, private beach dining, kayaking. Farewell beachside gala dinner under the stars." },
      { day: 6, title: "Departure", description: "Transfer back to Malé Airport for return flight to Kerala." },
    ],
  },
  {
    id: "thailand",
    slug: "thailand",
    name: "Thailand",
    region: "Southeast Asia",
    type: "international",
    country: "Thailand",
    price: 15000,
    priceLabel: "₹15,000 onwards",
    image: "https://images.unsplash.com/photo-1528181304800-259b08848526?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1528181304800-259b08848526?w=1920&q=90",
    tagline: "Land of Smiles",
    description: "Thailand is Southeast Asia's most versatile destination — from the neon-lit chaos of Bangkok's markets to the serene white-sand beaches of Krabi and Phuket, the ancient temple complexes of Chiang Mai, and the emerald islands of Koh Samui. It offers extraordinary food, genuine warmth, and remarkable value that make it India's most popular international destination.",
    bestTime: "November – March",
    duration: "6–8 Days",
    type_label: "Beach & Culture",
    includes: ["International Flights", "Hotel Accommodation", "Airport Transfers", "Breakfast Daily", "City Tours", "24/7 Support"],
    itinerary: [
      { day: 1, title: "Arrival in Bangkok", description: "Fly from Kerala (direct or via Colombo) to Bangkok Suvarnabhumi. Transfer to hotel in Sukhumvit. Evening at Asiatique night market on the Chao Phraya River." },
      { day: 2, title: "Bangkok Grand Tour", description: "Morning at Grand Palace and Wat Phra Kaew (Temple of the Emerald Buddha). Afternoon boat ride on the klongs (canals). Chatuchak Weekend Market in the evening." },
      { day: 3, title: "Bangkok → Krabi", description: "Morning flight to Krabi. Longtail boat to Railay Beach — accessible only by boat. Limestone karsts, crystal water, rock climbing. Sunset cocktails at the cliffside bar." },
      { day: 4, title: "Island Hopping", description: "Full day boat tour — Phra Nang Cave, Hong Island, Chicken Island, and Poda Island. Snorkeling in turquoise lagoons. BBQ beach dinner." },
      { day: 5, title: "Phi Phi Islands", description: "Speedboat day trip to Phi Phi Don and the famous Maya Bay (The Beach film location). Swimming in emerald water. Viewpoint hike." },
      { day: 6, title: "Free Day & Departure Prep", description: "Morning Thai cooking class. Afternoon Thai massage. Evening Muay Thai show. Farewell seafood dinner." },
      { day: 7, title: "Departure", description: "Transfer to Krabi or Phuket Airport for return flight to Kerala." },
    ],
  },
  {
    id: "vietnam",
    slug: "vietnam",
    name: "Vietnam",
    region: "Southeast Asia",
    type: "international",
    country: "Vietnam",
    price: 8000,
    priceLabel: "₹8,000 onwards",
    image: "https://images.unsplash.com/photo-1557750255-c76072a7aad1?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1557750255-c76072a7aad1?w=1920&q=90",
    tagline: "Where Ancient Meets Vivid",
    description: "Vietnam is a country of staggering beauty and contrasts — limestone pillars rising from emerald bays in Ha Long, French colonial architecture lining the lantern-lit streets of Hoi An, vibrant street food culture in Hanoi, and the electric energy of Ho Chi Minh City. A country that surprises every first-time visitor.",
    bestTime: "February – April, August – October",
    duration: "7–10 Days",
    type_label: "Culture & Adventure",
    includes: ["International Flights", "Hotel Accommodation", "Ha Long Bay Cruise", "Breakfast Daily", "City Tours", "24/7 Support"],
    itinerary: [
      { day: 1, title: "Arrive in Hanoi", description: "Fly from Kerala via Singapore or Bangkok to Hanoi. Transfer to Old Quarter hotel. Evening walk around Hoan Kiem Lake and Thap Rua Turtle Tower." },
      { day: 2, title: "Hanoi City", description: "Morning at Ho Chi Minh Mausoleum and Temple of Literature. Afternoon cycling through the 36 ancient guild streets. Street food tour — pho, banh mi, egg coffee." },
      { day: 3, title: "Ha Long Bay Overnight", description: "Board a traditional junk cruise on Ha Long Bay — UNESCO World Heritage Site. Kayaking through limestone caves. Cooking class on deck. Sunset on the bay." },
      { day: 4, title: "Ha Long → Hoi An", description: "Morning on the bay. Return to Hanoi, fly to Da Nang. Transfer to Hoi An Ancient Town. Evening lantern festival walk." },
      { day: 5, title: "Hoi An & My Son", description: "Explore Hoi An's silk lantern streets and old merchant houses. Afternoon day trip to My Son Cham temple ruins (4th century). Tailor-made clothing orders." },
      { day: 6, title: "Da Nang & Ba Na Hills", description: "Morning at the Golden Bridge at Ba Na Hills — held by two giant stone hands above the clouds. Afternoon at My Khe Beach." },
      { day: 7, title: "Ho Chi Minh City", description: "Fly south to Ho Chi Minh City. Reunification Palace tour. Cu Chi Tunnels — WWII underground network. Bui Vien walking street at night." },
      { day: 8, title: "Departure", description: "Final pho breakfast. Transfer to Tan Son Nhat Airport for return flight to Kerala." },
    ],
  },
  {
    id: "malaysia",
    slug: "malaysia",
    name: "Malaysia",
    region: "Southeast Asia",
    type: "international",
    country: "Malaysia",
    price: 12000,
    priceLabel: "₹12,000 onwards",
    image: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=1920&q=90",
    tagline: "Truly Asia",
    description: "Malaysia is Southeast Asia's most underrated gem — a seamless blend of Malay, Chinese, Indian, and indigenous cultures all coexisting in a mosaic of rainforests, colonial streets, and gleaming cityscapes. From the Petronas Twin Towers to the firefly rivers of Kuala Selangor and the pristine beaches of Langkawi, Malaysia delivers extraordinary diversity in a compact itinerary.",
    bestTime: "March – October",
    duration: "5–7 Days",
    type_label: "Culture & City",
    includes: ["International Flights", "Hotel Accommodation", "Airport Transfers", "Breakfast Daily", "City Tours", "24/7 Support"],
    itinerary: [
      { day: 1, title: "Arrive in Kuala Lumpur", description: "Direct flight from Kochi to KLIA. Transfer to Bukit Bintang hotel. Evening walk along Jalan Alor food street. Night view of the Petronas Towers." },
      { day: 2, title: "KL City Tour", description: "Morning at Petronas Twin Towers (Sky Bridge). Batu Caves Hindu temple complex. Afternoon at KL Forest Eco Park — canopy walkway. Little India at Brickfields." },
      { day: 3, title: "Langkawi Island", description: "Morning flight or ferry to Langkawi. Cable car to the peak — views of Thailand's islands. Seven Wells Waterfall. Mangrove kayaking." },
      { day: 4, title: "Langkawi Beach Day", description: "Pantai Cenang white sand beach. Underwater World aquarium. Eagle feeding at Dataran Lang. Island boat tour." },
      { day: 5, title: "Penang Georgetown", description: "Ferry to Penang. Georgetown Heritage Zone street art and colonial architecture. Famous Penang hawker food — char koay teow, asam laksa." },
      { day: 6, title: "Cameron Highlands", description: "Drive to Cameron Highlands tea plantations. Boh Tea Estate tour and tasting. Strawberry farms and butterfly gardens." },
      { day: 7, title: "Departure", description: "Return to Kuala Lumpur for departure flight back to Kerala." },
    ],
  },
  {
    id: "singapore",
    slug: "singapore",
    name: "Singapore",
    region: "Southeast Asia",
    type: "international",
    country: "Singapore",
    price: 19000,
    priceLabel: "₹19,000 onwards",
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80",
    heroImage: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=1920&q=90",
    tagline: "The City of the Future",
    description: "Singapore is the world's most futuristic city — where supertrees glow neon above the Gardens by the Bay, infinity pools overlook a skyline of glass and light, and hawker centres serve some of the world's best street food. As a travel hub, it's the perfect gateway to Southeast Asia, and as a destination in itself, it never fails to dazzle.",
    bestTime: "February – April, July – September",
    duration: "4–5 Days",
    type_label: "City & Urban",
    includes: ["International Flights", "Hotel Accommodation", "Airport Transfers", "Breakfast Daily", "Sentosa Island Pass", "24/7 Support"],
    itinerary: [
      { day: 1, title: "Arrival in Singapore", description: "Fly from Kerala (direct or via KL) to Changi Airport — multiple airline options. Transfer to your hotel in Marina Bay. Evening at Gardens by the Bay light show (free)." },
      { day: 2, title: "Marina Bay & Sentosa", description: "Morning Marina Bay Sands SkyPark for panoramic views. Afternoon at Sentosa Island — Universal Studios Singapore, S.E.A. Aquarium, Siloso Beach." },
      { day: 3, title: "Culture & Heritage", description: "Explore Chinatown and the Buddha Tooth Relic Temple. Little India at Mustafa Centre. Arab Street and Sultan Mosque. Evening Raffles Hotel Singapore Sling." },
      { day: 4, title: "City & Science", description: "ArtScience Museum. Fort Canning Park. Orchard Road shopping. Clarke Quay riverfront dinner. Night Safari at Jurong Bird Park." },
      { day: 5, title: "Departure", description: "Morning visit to Jewel Changi Airport — a marvel of architecture with indoor waterfall. Transfer for departure flight." },
    ],
  },
];

export function getDestinationBySlug(slug: string): Destination | undefined {
  return destinations.find((d) => d.slug === slug);
}

export const featuredDestinations = destinations.filter(d =>
  ["kashmir", "bali", "maldives", "wayanad", "thailand", "manali"].includes(d.slug)
);
